# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OsmosisdTest < Formula
  desc "osmosisd binary to interact with the Osmosis network"
  homepage "https://gihub.com/osmosis-labs/osmosis"
  version "20.0.0"

  on_macos do
    url "https://github.com/niccoloraspa/osmosis/releases/download/v20.0.0/osmosisd-20.0.0-darwin-all"
    sha256 "15aac411abbc3552d6fddce98158e81bde44cbb7821ec154a52ea3535e75aab1"

    def install
      bin.install 'osmosisd'
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/niccoloraspa/osmosis/releases/download/v20.0.0/osmosisd-20.0.0-linux-amd64"
      sha256 "e6fa428e887d86708b9fd8ac3212d9e39befc804630a389dabb2ca034979adbb"

      def install
        bin.install 'osmosisd'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/niccoloraspa/osmosis/releases/download/v20.0.0/osmosisd-20.0.0-linux-arm64"
      sha256 "1d277a31ca07f3f2b2347f7aa3d7821446b2da8a4fff2f4b94d4188aa2490b8a"

      def install
        bin.install 'osmosisd'
      end
    end
  end

  conflicts_with "osmosisd"

  test do
    system "#{bin}/osmosisd version"
  end
end
