# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OsmosisdTest < Formula
  desc "osmosisd binary to interact with the Osmosis network"
  homepage "https://gihub.com/osmosis-labs/osmosis"
  version "16.0.0"

  on_macos do
    url "https://github.com/niccoloraspa/osmosis/releases/download/v16.0.0/osmosisd-16.0.0-darwin-all"
    sha256 "52ec505cf30577d6a34e03f348701aef74fa3ddd00cf80854b35d9bcc64b4fa4"

    def install
      bin.install 'osmosisd'
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/niccoloraspa/osmosis/releases/download/v16.0.0/osmosisd-16.0.0-linux-arm64"
      sha256 "6f16e7bdaaba118498e0ea262f540ea2e996e16718256d2194b9ed9385d7c41d"

      def install
        bin.install 'osmosisd'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/niccoloraspa/osmosis/releases/download/v16.0.0/osmosisd-16.0.0-linux-amd64"
      sha256 "4b9329121cee800bab830a25106a8c68187b2967a31a43a403fe81335f945d56"

      def install
        bin.install 'osmosisd'
      end
    end
  end

  conflicts_with "osmosisd"

  test do
    system "#{bin}/osmosisd version"
  end
end
